const CHAMPIONS_SHIP_COLLECTION = 'chanpions_ships';
const TEAM_COLLECTION = 'teams';
const CLASSIFICATION_COLLECTION = 'classification';


export {
  CHAMPIONS_SHIP_COLLECTION,
  TEAM_COLLECTION,
  CLASSIFICATION_COLLECTION
};
