const CHAMPIONS_SHIP_COLLECTION = 'chanpionShips';
const TEAM_COLLECTION = 'teams';
const CLASSIFICATION_COLLECTION = 'classifications';


export {
  CHAMPIONS_SHIP_COLLECTION,
  TEAM_COLLECTION,
  CLASSIFICATION_COLLECTION
};
